title: Building Jekyll
description: A simple Jekyll website built from scratch.
# baseurl: "/building-jekyll"
url: "https://building-jekyll.netlify.com/"
author:
  name: Silvio Gulizia
  image: /assets/images/silviogulizia.jpg

twitter:
  twitter: silviogulizia
  card: summary_large_image

permalink: /:title

include: ['_pages']

collections:
  projects:
    output: true
  micro:
    output: true
    permalink: /micro/:title

defaults:
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - 
    scope:
      path: ""
      type: "project"
    values:
      layout: "project"
  - 
    scope:
      path: ""
      type: "micro"
    values:
      layout: "post"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
