title: Building Jekyll
description: A simple Jekyll website built from scratch.
# baseurl: "/building-jekyll"
# url: "https://sigul.netlify.com/building-jekyll"
author:
  twitter: silviogulizia

permalink: /:title

include: ['_pages']

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "project"
    values:
      layout: "project"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
